#include "memlayout.h"

uservec:
    #
    # csrw = control and status register write, so this instruction
    # write in the cpu's csr register
    #
    # scratch register are the register to store the value temporarily. 
    # sscratch means supervisor scratch register
    #

    # so here we are copying the value of the a0 in sscratch register
    csrw sscratch, a0

    li a0, TRAPFRAME

    # save the user registers in TRAPFRAME
        sd ra, 40(a0)
        sd sp, 48(a0)
        sd gp, 56(a0)
        sd tp, 64(a0)
        sd t0, 72(a0)
        sd t1, 80(a0)
        sd t2, 88(a0)
        sd s0, 96(a0)
        sd s1, 104(a0)
        sd a1, 120(a0)
        sd a2, 128(a0)
        sd a3, 136(a0)
        sd a4, 144(a0)
        sd a5, 152(a0)
        sd a6, 160(a0)
        sd a7, 168(a0)
        sd s2, 176(a0)
        sd s3, 184(a0)
        sd s4, 192(a0)
        sd s5, 200(a0)
        sd s6, 208(a0)
        sd s7, 216(a0)
        sd s8, 224(a0)
        sd s9, 232(a0)
        sd s10, 240(a0)
        sd s11, 248(a0)
        sd t3, 256(a0)
        sd t4, 264(a0)
        sd t5, 272(a0)
        sd t6, 280(a0)

        // t0 is also temporary register
        csrr t0 sscratch
        sd t0, 112(a0)

